package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Cockpit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cockpit.id
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cockpit.diagramIDs
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    private String diagramids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cockpit.name
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cockpit.user_id
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cockpit.info
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cockpit.id
     *
     * @return the value of cockpit.id
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cockpit.id
     *
     * @param id the value for cockpit.id
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cockpit.diagramIDs
     *
     * @return the value of cockpit.diagramIDs
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public String getDiagramids() {
        return diagramids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cockpit.diagramIDs
     *
     * @param diagramids the value for cockpit.diagramIDs
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public void setDiagramids(String diagramids) {
        this.diagramids = diagramids == null ? null : diagramids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cockpit.name
     *
     * @return the value of cockpit.name
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cockpit.name
     *
     * @param name the value for cockpit.name
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cockpit.user_id
     *
     * @return the value of cockpit.user_id
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cockpit.user_id
     *
     * @param userId the value for cockpit.user_id
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cockpit.info
     *
     * @return the value of cockpit.info
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cockpit.info
     *
     * @param info the value for cockpit.info
     *
     * @mbggenerated Fri Jun 21 15:38:15 CST 2019
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}