package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Dashboard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard.id
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard.graph_ids
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    private String graphIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard.user_id
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    private String userId;
    /**
     *
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard.id
     *
     * @return the value of dashboard.id
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard.id
     *
     * @param id the value for dashboard.id
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard.graph_ids
     *
     * @return the value of dashboard.graph_ids
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    public String getGraphIds() {
        return graphIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard.graph_ids
     *
     * @param graphIds the value for dashboard.graph_ids
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    public void setGraphIds(String graphIds) {
        this.graphIds = graphIds == null ? null : graphIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard.user_id
     *
     * @return the value of dashboard.user_id
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard.user_id
     *
     * @param userId the value for dashboard.user_id
     *
     * @mbggenerated Fri Nov 16 11:00:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     *
     * @return
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

}