package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class DataSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.id
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.file_name
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.file_url
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.file_type
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    private String fileType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.id
     *
     * @return the value of data_source.id
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.id
     *
     * @param id the value for data_source.id
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.file_name
     *
     * @return the value of data_source.file_name
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.file_name
     *
     * @param fileName the value for data_source.file_name
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.file_url
     *
     * @return the value of data_source.file_url
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.file_url
     *
     * @param fileUrl the value for data_source.file_url
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.file_type
     *
     * @return the value of data_source.file_type
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.file_type
     *
     * @param fileType the value for data_source.file_type
     *
     * @mbggenerated Thu Nov 22 15:27:19 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }
}