package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class DiagramSql {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.diagramid
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    private Long diagramid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.data_source_id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    private String dataSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.user_id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.sqlinfo
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    private String sqlinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.id
     *
     * @return the value of diagram_sql.id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.id
     *
     * @param id the value for diagram_sql.id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.diagramid
     *
     * @return the value of diagram_sql.diagramid
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public Long getDiagramid() {
        return diagramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.diagramid
     *
     * @param diagramid the value for diagram_sql.diagramid
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public void setDiagramid(Long diagramid) {
        this.diagramid = diagramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.data_source_id
     *
     * @return the value of diagram_sql.data_source_id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.data_source_id
     *
     * @param dataSourceId the value for diagram_sql.data_source_id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId == null ? null : dataSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.user_id
     *
     * @return the value of diagram_sql.user_id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.user_id
     *
     * @param userId the value for diagram_sql.user_id
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.sqlinfo
     *
     * @return the value of diagram_sql.sqlinfo
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public String getSqlinfo() {
        return sqlinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.sqlinfo
     *
     * @param sqlinfo the value for diagram_sql.sqlinfo
     *
     * @mbggenerated Fri Jun 21 18:59:30 CST 2019
     */
    public void setSqlinfo(String sqlinfo) {
        this.sqlinfo = sqlinfo == null ? null : sqlinfo.trim();
    }
}