package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class DiagramSql {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.diagramid
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private Long diagramid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.data_source_id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private String dataSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.user_id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.sqlinfo
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private String sqlinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.dims
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private String dims;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.meas
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private String meas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.rows
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private String rows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram_sql.update_time
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.id
     *
     * @return the value of diagram_sql.id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.id
     *
     * @param id the value for diagram_sql.id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.diagramid
     *
     * @return the value of diagram_sql.diagramid
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public Long getDiagramid() {
        return diagramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.diagramid
     *
     * @param diagramid the value for diagram_sql.diagramid
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setDiagramid(Long diagramid) {
        this.diagramid = diagramid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.data_source_id
     *
     * @return the value of diagram_sql.data_source_id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.data_source_id
     *
     * @param dataSourceId the value for diagram_sql.data_source_id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId == null ? null : dataSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.user_id
     *
     * @return the value of diagram_sql.user_id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.user_id
     *
     * @param userId the value for diagram_sql.user_id
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.sqlinfo
     *
     * @return the value of diagram_sql.sqlinfo
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public String getSqlinfo() {
        return sqlinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.sqlinfo
     *
     * @param sqlinfo the value for diagram_sql.sqlinfo
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setSqlinfo(String sqlinfo) {
        this.sqlinfo = sqlinfo == null ? null : sqlinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.dims
     *
     * @return the value of diagram_sql.dims
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public String getDims() {
        return dims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.dims
     *
     * @param dims the value for diagram_sql.dims
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setDims(String dims) {
        this.dims = dims == null ? null : dims.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.meas
     *
     * @return the value of diagram_sql.meas
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public String getMeas() {
        return meas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.meas
     *
     * @param meas the value for diagram_sql.meas
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setMeas(String meas) {
        this.meas = meas == null ? null : meas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.rows
     *
     * @return the value of diagram_sql.rows
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public String getRows() {
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.rows
     *
     * @param rows the value for diagram_sql.rows
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setRows(String rows) {
        this.rows = rows == null ? null : rows.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram_sql.update_time
     *
     * @return the value of diagram_sql.update_time
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram_sql.update_time
     *
     * @param updateTime the value for diagram_sql.update_time
     *
     * @mbggenerated Sat Jun 22 18:54:41 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}