package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class Diagram {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.id
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.classification
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.user_id
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.data_source_id
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String dataSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.name
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.saved
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String saved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.update_time
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.association_ids
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String associationIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagram.chart
     *
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    private String chart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.id
     *
     * @return the value of diagram.id
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.id
     *
     * @param id the value for diagram.id
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.classification
     *
     * @return the value of diagram.classification
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.classification
     *
     * @param classification the value for diagram.classification
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.user_id
     *
     * @return the value of diagram.user_id
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.user_id
     *
     * @param userId the value for diagram.user_id
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.data_source_id
     *
     * @return the value of diagram.data_source_id
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.data_source_id
     *
     * @param dataSourceId the value for diagram.data_source_id
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId == null ? null : dataSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.name
     *
     * @return the value of diagram.name
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.name
     *
     * @param name the value for diagram.name
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.saved
     *
     * @return the value of diagram.saved
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getSaved() {
        return saved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.saved
     *
     * @param saved the value for diagram.saved
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setSaved(String saved) {
        this.saved = saved == null ? null : saved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.update_time
     *
     * @return the value of diagram.update_time
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.update_time
     *
     * @param updateTime the value for diagram.update_time
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.association_ids
     *
     * @return the value of diagram.association_ids
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getAssociationIds() {
        return associationIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.association_ids
     *
     * @param associationIds the value for diagram.association_ids
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setAssociationIds(String associationIds) {
        this.associationIds = associationIds == null ? null : associationIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagram.chart
     *
     * @return the value of diagram.chart
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public String getChart() {
        return chart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagram.chart
     *
     * @param chart the value for diagram.chart
     * @mbggenerated Tue Nov 26 10:21:45 CST 2019
     */
    public void setChart(String chart) {
        this.chart = chart == null ? null : chart.trim();
    }
}