package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class DrillDim {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drill_dim.id
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drill_dim.tablename
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drill_dim.dims
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    private String dims;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drill_dim.id
     *
     * @return the value of drill_dim.id
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drill_dim.id
     *
     * @param id the value for drill_dim.id
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drill_dim.tablename
     *
     * @return the value of drill_dim.tablename
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drill_dim.tablename
     *
     * @param tablename the value for drill_dim.tablename
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drill_dim.dims
     *
     * @return the value of drill_dim.dims
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    public String getDims() {
        return dims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drill_dim.dims
     *
     * @param dims the value for drill_dim.dims
     *
     * @mbggenerated Wed Mar 13 10:43:18 CST 2019
     */
    public void setDims(String dims) {
        this.dims = dims == null ? null : dims.trim();
    }
}