package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class FaltTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column falt_table.id
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column falt_table.model
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column falt_table.table_sql
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    private String tableSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column falt_table.project
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column falt_table.name
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column falt_table.tables
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    private String tables;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column falt_table.id
     *
     * @return the value of falt_table.id
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column falt_table.id
     *
     * @param id the value for falt_table.id
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column falt_table.model
     *
     * @return the value of falt_table.model
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column falt_table.model
     *
     * @param model the value for falt_table.model
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column falt_table.table_sql
     *
     * @return the value of falt_table.table_sql
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public String getTableSql() {
        return tableSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column falt_table.table_sql
     *
     * @param tableSql the value for falt_table.table_sql
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public void setTableSql(String tableSql) {
        this.tableSql = tableSql == null ? null : tableSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column falt_table.project
     *
     * @return the value of falt_table.project
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column falt_table.project
     *
     * @param project the value for falt_table.project
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column falt_table.name
     *
     * @return the value of falt_table.name
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column falt_table.name
     *
     * @param name the value for falt_table.name
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column falt_table.tables
     *
     * @return the value of falt_table.tables
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public String getTables() {
        return tables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column falt_table.tables
     *
     * @param tables the value for falt_table.tables
     *
     * @mbggenerated Thu Nov 22 10:00:27 CST 2018
     */
    public void setTables(String tables) {
        this.tables = tables == null ? null : tables.trim();
    }
}