package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class StoryItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_item.id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_item.diagram_id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    private String diagramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story_item.description
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    private String description;

    private String storyId;
    public String getStoryId() {
        return storyId;
    }
    public void setStoryId(String storyId) {
        this.storyId = storyId == null ? null : storyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_item.id
     *
     * @return the value of story_item.id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_item.id
     *
     * @param id the value for story_item.id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_item.diagram_id
     *
     * @return the value of story_item.diagram_id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public String getDiagramId() {
        return diagramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_item.diagram_id
     *
     * @param diagramId the value for story_item.diagram_id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public void setDiagramId(String diagramId) {
        this.diagramId = diagramId == null ? null : diagramId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story_item.description
     *
     * @return the value of story_item.description
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story_item.description
     *
     * @param description the value for story_item.description
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}