package bupt.edu.cn.web.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Story {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.content
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column story.user_id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    private String userId;
    private String storyName;

    public String getStoryName() {
        return storyName;
    }
    public void setStoryName(String storyName) {
        this.storyName = storyName == null ? null : storyName.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.id
     *
     * @return the value of story.id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.id
     *
     * @param id the value for story.id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.content
     *
     * @return the value of story.content
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.content
     *
     * @param content the value for story.content
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column story.user_id
     *
     * @return the value of story.user_id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column story.user_id
     *
     * @param userId the value for story.user_id
     *
     * @mbggenerated Sun Dec 09 15:56:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}