spring:
  datasource:
    url: jdbc:mysql://10.108.211.136:3306/preprocess?useSSL=false&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/preprocess?useSSL=false&characterEncoding=utf-8
    username: root
    password: 'mySQL#h@d00p'
#    password: '0000'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 6993
  tomcat:
    uri-encoding: UTF-8
#  additional-tld-skip-patterns:
#    tldSkipPatterns: derbyLocale_*.jar,jaxb-api.jar,jsr173_1.0_api.jar,jaxb1-impl.jar,activation.jar

